const works={rug:{image:'Rug.webp',title:'Colour, held in yarn',titleJa:'糸に宿る色',kind:'Textile work',description:'An abstract hand-tufted rug from the studio archive. Colour and texture give its organic forms a physical presence.',descriptionJa:'スタジオのアーカイブより。抽象的なかたちを、色と質感のあるハンドタフテッドのラグに。'},pouch:{image:'Minipouch.webp',title:'Minipouch',titleJa:'ミニポーチ',kind:'Small object',description:'A small knitted pouch with a cord and bead. A tactile object made to be held and carried.',descriptionJa:'コードとビーズを添えた、小さな編みのポーチ。手に触れ、持ち歩くためのもの。'},zine:{image:'work-prato.webp',title:'In good company with FF',titleJa:'In good company with FF',kind:'Publication',description:'A publication from the studio archive, bringing printed matter and a three-dimensional mesh form into the same encounter.',descriptionJa:'印刷物と立体的なメッシュのかたちが出会う、スタジオの出版物。'},study:{image:'work-zine.webp',title:'Case Study 1',titleJa:'Case Study 1',kind:'Publication / Textile research',description:'A textile case-study publication associated with Prato. Photographs and notes bring the material and its surroundings onto the page.',descriptionJa:'プラートに関するテキスタイルのケーススタディ。写真と記録を通して、素材とその周囲を紙の上に。'}};
let language='en',currentWork=null,activeFilter='all';
const dialog=document.getElementById('work-dialog');
function updateCount(){const n=document.querySelectorAll('.works article:not([hidden])').length;document.getElementById('count').textContent=language==='ja'?`${n} 点`:`${n} works`;}
function renderWork(key){const w=works[key];document.getElementById('work-title').textContent=language==='ja'?w.titleJa:w.title;document.getElementById('work-kind').textContent=w.kind;document.getElementById('work-description').textContent=language==='ja'?w.descriptionJa:w.description;document.getElementById('work-image').src='assets/'+w.image;document.getElementById('work-image').alt=language==='ja'?w.titleJa:w.title;document.getElementById('work-contact').href='mailto:info.studiocerebrum@gmail.com?subject='+encodeURIComponent('Enquiry: '+w.title);}
document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{activeFilter=button.dataset.filter;document.querySelectorAll('[data-filter]').forEach(b=>{b.classList.toggle('active',b===button);b.setAttribute('aria-pressed',String(b===button));});document.querySelectorAll('.works article').forEach(article=>{article.hidden=activeFilter!=='all'&&article.dataset.category!==activeFilter;});updateCount();}));
document.querySelectorAll('[data-work]').forEach(button=>button.addEventListener('click',()=>{currentWork=button.dataset.work;renderWork(currentWork);dialog.showModal();}));
document.getElementById('close-dialog').addEventListener('click',()=>dialog.close());
document.getElementById('language').addEventListener('click',()=>{language=language==='en'?'ja':'en';document.documentElement.lang=language;document.querySelectorAll('[data-en][data-ja]').forEach(el=>el.innerHTML=el.dataset[language]);const b=document.getElementById('language');b.textContent=language==='en'?'日本語':'English';b.setAttribute('aria-label',language==='en'?'Switch to Japanese':'Switch to English');if(currentWork)renderWork(currentWork);updateCount();});
